POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxpaXNhTWlpc2EiLCJpZCI6IjY2NTMzODcyNmIwODZmZTJlOGRmNDFmYiIsImlhdCI6MTcxNjczMDQxOX0.u25-iYLKhUFGk9adF15aT0npQujyG0WtF2rSnCqnAPA


{
    "author": "Leo Jooma", 
    "title": "Leon blogi",
    "userId": "665338726b086fe2e8df41fb",
    "url": "www.leonblogi1",
    "likes": 5
}

